
logging:
  path: /var/log
---
spring:
  profiles: cloud
server:
  port: 9009
eureka:
  client:
    serviceUrl:
      defaultZone: http://pro-discovery:8761/eureka/
  instance:
    hostname: pro-webui
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true
    
---
spring:
  profiles: development
server:
  port: 9009
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true
    
#zuul:
 # routes:
 #   members: /members/**
    